apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: anotherclass-222-dev
commonLabels:
  version: 2.0.0
resources:
  - ../../base
patches:
  # 이 kustomize 의 형제로 위치한 매니페스트 중에 overlay 로 사용할 매니페스트들 지정
  - path: configmap.yaml
  - path: deployment-spec.yaml
  - path: deployment-ver.yaml
  - path: secret.yaml
  - path: service.yaml